# Generated by Django 5.1.2 on 2024-12-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='images',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
