# Generated by Django 5.1.2 on 2024-12-11 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_dish_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='images',
        ),
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dishes/'),
            preserve_default=False,
        ),
    ]
