# Generated by Django 5.1.2 on 2024-12-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_dish_images_dish_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
        migrations.CreateModel(
            name='DishPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dishes/photos/')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='restaurant.dish')),
            ],
        ),
    ]
